"""create table for tony award

Revision ID: 061b0d0d7961
Revises: 61b9348a2960
Create Date: 2021-01-24 18:25:52.949310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061b0d0d7961'
down_revision = '61b9348a2960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
