"""hi yaakov

Revision ID: 0dcb5aecebf1
Revises: cf273f761312
Create Date: 2021-01-12 11:37:42.281675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dcb5aecebf1'
down_revision = 'cf273f761312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
