"""adding racial identity

Revision ID: 288cb2a0dcd9
Revises: c261b391db87
Create Date: 2021-01-11 11:48:25.203716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288cb2a0dcd9'
down_revision = 'c261b391db87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racial_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='constrain to lowercase values'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='This field is optional.'),
    sa.Column('date_created', sa.DateTime(), nullable=False, comment='internally managed.'),
    sa.Column('date_updated', sa.DateTime(), nullable=True, comment='internally managed.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('racial_identity_association',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('racial_identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['racial_identity_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'racial_identity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('racial_identity_association')
    op.drop_table('racial_identity')
    # ### end Alembic commands ###
