"""upgrading this through shell commands

Revision ID: 35fc75589ff8
Revises: 8b2b008ac109
Create Date: 2021-01-10 21:08:45.900269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35fc75589ff8'
down_revision = '8b2b008ac109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_instantiated', sa.DateTime(), nullable=False, comment='internally managed'),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('opening_date', sa.DateTime(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('previews_date', sa.DateTime(), nullable=True),
    sa.Column('year', mysql.YEAR(), nullable=True),
    sa.Column('theatre_name', sa.String(length=60), nullable=True),
    sa.Column('production_type', sa.String(length=20), nullable=True),
    sa.Column('show_type', sa.String(length=20), nullable=True),
    sa.Column('show_type_simple', sa.String(length=20), nullable=True),
    sa.Column('intermissions', mysql.TINYINT(), nullable=True),
    sa.Column('n_performances', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('show_never_opened', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revival', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pre_broadway', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('limited_run', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('repertory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('other_titles', sa.String(length=300), nullable=True, comment='should this be made into an association table?'),
    sa.Column('official_website', sa.String(length=100), nullable=True, comment='this should be made into an associated table...'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_year'), 'shows', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_year'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
