"""upgrading this through shell commands

Revision ID: 5d1d61e0b4e3
Revises: 1349050f3bd6
Create Date: 2021-01-10 21:20:56.452073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d1d61e0b4e3'
down_revision = '1349050f3bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_instantiated', sa.DateTime(), nullable=False, comment='internally managed'),
    sa.Column('theatre_name', sa.String(length=200), nullable=True),
    sa.Column('street_address', sa.String(length=300), nullable=True),
    sa.Column('address_locality', sa.String(length=100), nullable=True),
    sa.Column('address_region', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('year_closed', mysql.YEAR(), nullable=True),
    sa.Column('year_demolished', mysql.YEAR(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_instantiated', sa.DateTime(), nullable=False, comment='internally managed'),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('opening_date', sa.DateTime(), nullable=True),
    sa.Column('closing_date', sa.DateTime(), nullable=True),
    sa.Column('previews_date', sa.DateTime(), nullable=True),
    sa.Column('year', mysql.YEAR(), nullable=True),
    sa.Column('theatre_id', sa.Integer(), nullable=True),
    sa.Column('scraped_theatre_name', sa.String(length=60), nullable=True),
    sa.Column('production_type', sa.String(length=20), nullable=True),
    sa.Column('show_type', sa.String(length=20), nullable=True),
    sa.Column('show_type_simple', sa.String(length=20), nullable=True),
    sa.Column('intermissions', mysql.TINYINT(), nullable=True),
    sa.Column('n_performances', sa.Integer(), nullable=True),
    sa.Column('run_time', sa.Integer(), nullable=True),
    sa.Column('show_never_opened', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('revival', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('pre_broadway', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('limited_run', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('repertory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('other_titles', sa.String(length=300), nullable=True, comment='should this be made into an association table?'),
    sa.Column('official_website', sa.String(length=100), nullable=True, comment='this should be made into an associated table...'),
    sa.ForeignKeyConstraint(['theatre_id'], ['theatre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_closing_date'), 'show', ['closing_date'], unique=False)
    op.create_index(op.f('ix_show_opening_date'), 'show', ['opening_date'], unique=False)
    op.create_index(op.f('ix_show_theatre_id'), 'show', ['theatre_id'], unique=False)
    op.create_index(op.f('ix_show_year'), 'show', ['year'], unique=False)
    op.drop_index('ix_shows_closing_date', table_name='shows')
    op.drop_index('ix_shows_opening_date', table_name='shows')
    op.drop_index('ix_shows_year', table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_instantiated', mysql.DATETIME(), nullable=False, comment='internally managed'),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('opening_date', mysql.DATETIME(), nullable=True),
    sa.Column('closing_date', mysql.DATETIME(), nullable=True),
    sa.Column('previews_date', mysql.DATETIME(), nullable=True),
    sa.Column('year', mysql.YEAR(), nullable=True),
    sa.Column('theatre_name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('production_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('show_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('show_type_simple', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('intermissions', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('n_performances', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('run_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_never_opened', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('revival', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('pre_broadway', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('limited_run', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('repertory', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('other_titles', mysql.VARCHAR(length=300), nullable=True, comment='should this be made into an association table?'),
    sa.Column('official_website', mysql.VARCHAR(length=100), nullable=True, comment='this should be made into an associated table...'),
    sa.CheckConstraint('(`limited_run` in (0,1))', name='shows_chk_4'),
    sa.CheckConstraint('(`pre_broadway` in (0,1))', name='shows_chk_3'),
    sa.CheckConstraint('(`repertory` in (0,1))', name='shows_chk_5'),
    sa.CheckConstraint('(`revival` in (0,1))', name='shows_chk_2'),
    sa.CheckConstraint('(`show_never_opened` in (0,1))', name='shows_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_shows_year', 'shows', ['year'], unique=False)
    op.create_index('ix_shows_opening_date', 'shows', ['opening_date'], unique=False)
    op.create_index('ix_shows_closing_date', 'shows', ['closing_date'], unique=False)
    op.drop_index(op.f('ix_show_year'), table_name='show')
    op.drop_index(op.f('ix_show_theatre_id'), table_name='show')
    op.drop_index(op.f('ix_show_opening_date'), table_name='show')
    op.drop_index(op.f('ix_show_closing_date'), table_name='show')
    op.drop_table('show')
    op.drop_table('theatre')
    # ### end Alembic commands ###
