"""checking to make sure this still works

Revision ID: 61b9348a2960
Revises: 37aa4277ce51
Create Date: 2021-01-17 20:53:18.162678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61b9348a2960'
down_revision = '37aa4277ce51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
