"""adding the rest of the tables now

Revision ID: 744a5120d5be
Revises: f3af77f05dd6
Create Date: 2021-01-11 11:41:25.193719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '744a5120d5be'
down_revision = 'f3af77f05dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_edits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edit_id', sa.Integer(), nullable=False),
    sa.Column('edit_date', sa.DateTime(), nullable=False),
    sa.Column('table_name', sa.String(length=80), nullable=False),
    sa.Column('value_primary_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('field_type', sa.String(length=40), nullable=False),
    sa.Column('value_pre', mysql.TEXT(), nullable=True),
    sa.Column('value_post', mysql.TEXT(), nullable=False),
    sa.Column('edit_by', sa.String(length=60), nullable=False),
    sa.Column('edit_comment', mysql.TEXT(), nullable=True),
    sa.Column('edit_citation', sa.String(length=200), nullable=True),
    sa.Column('approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('approved_by', sa.String(length=60), nullable=False),
    sa.Column('approved_comment', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'edit_id')
    )
    op.create_table('gender_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='constrain to lowercase values'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='This field is optional.'),
    sa.Column('date_created', sa.DateTime(), nullable=False, comment='internally managed.'),
    sa.Column('date_updated', sa.DateTime(), nullable=True, comment='internally managed.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False, comment='constrain to lowercase values'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='This field is optional.'),
    sa.Column('date_created', sa.DateTime(), nullable=False, comment='internally managed.'),
    sa.Column('date_updated', sa.DateTime(), nullable=True, comment='internally managed.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False, comment='internally managed.'),
    sa.Column('date_updated', sa.DateTime(), nullable=True, comment='internally managed.'),
    sa.Column('name_title', sa.String(length=10), nullable=True),
    sa.Column('f_name', sa.String(length=40), nullable=True),
    sa.Column('m_name', sa.String(length=40), nullable=True),
    sa.Column('l_name', sa.String(length=40), nullable=True),
    sa.Column('name_suffix', sa.String(length=10), nullable=True),
    sa.Column('name_nickname', sa.String(length=40), nullable=True),
    sa.Column('broadway_world_url', sa.String(length=120), nullable=True, comment="This person's url on broadwayworld.com"),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('year_of_birth', mysql.YEAR(), nullable=True),
    sa.Column('country_of_birth', sa.String(length=40), nullable=True),
    sa.Column('fluent_languages', sa.String(length=80), nullable=True),
    sa.Column('gender_identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gender_identity_id'], ['gender_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows_roles_link',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', mysql.TEXT(), nullable=True, comment='Allow text of unlimited length'),
    sa.Column('url', sa.String(length=200), nullable=True, comment='This field is optional.'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'show_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows_roles_link')
    op.drop_table('person')
    op.drop_table('role')
    op.drop_table('gender_identity')
    op.drop_table('data_edits')
    # ### end Alembic commands ###
