"""create table for tony award

Revision ID: 827fb4ff41a0
Revises: 061b0d0d7961
Create Date: 2021-01-24 18:27:14.680332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827fb4ff41a0'
down_revision = '061b0d0d7961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tony_award',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('name', sa.String(length=120), nullable=False, comment='The name of a Tony Award (this changes over time though...)'),
    sa.Column('description', sa.String(length=300), nullable=True, comment='This field is optional.'),
    sa.Column('date_created', sa.DateTime(), nullable=False, comment='internally managed.'),
    sa.Column('date_updated', sa.DateTime(), nullable=True, comment='internally managed.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='This table represents a tony award instance. (Example: Best Lighting Design for a Musical.)'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tony_award')
    # ### end Alembic commands ###
