"""fixing primary keys for racial identity

Revision ID: 829b9fef152b
Revises: 288cb2a0dcd9
Create Date: 2021-01-11 11:49:26.915867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829b9fef152b'
down_revision = '288cb2a0dcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('racial_identity_association_ibfk_2', 'racial_identity_association', type_='foreignkey')
    op.create_foreign_key(None, 'racial_identity_association', 'racial_identity', ['racial_identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racial_identity_association', type_='foreignkey')
    op.create_foreign_key('racial_identity_association_ibfk_2', 'racial_identity_association', 'person', ['racial_identity_id'], ['id'])
    # ### end Alembic commands ###
