"""upgrading this through shell commands

Revision ID: 8b2b008ac109
Revises: 8360394286bd
Create Date: 2021-01-10 21:06:22.174517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2b008ac109'
down_revision = '8360394286bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
