"""link tony awards to everything else

Revision ID: 91a0638c1f15
Revises: 827fb4ff41a0
Create Date: 2021-01-24 18:36:01.312819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91a0638c1f15'
down_revision = '827fb4ff41a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tony_award_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('date_awarded', mysql.YEAR(), nullable=False, comment='When was this award awarded?'),
    sa.ForeignKeyConstraint(['award_id'], ['tony_award.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id', 'award_id'),
    comment='This table represents a tony award instance. (Example: Best Lighting Design for a Musical.)'
    )
    op.create_index(op.f('ix_tony_award_link_person_id'), 'tony_award_link', ['person_id'], unique=False)
    op.create_index(op.f('ix_tony_award_link_role_id'), 'tony_award_link', ['role_id'], unique=False)
    op.create_index(op.f('ix_tony_award_link_show_id'), 'tony_award_link', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tony_award_link_show_id'), table_name='tony_award_link')
    op.drop_index(op.f('ix_tony_award_link_role_id'), table_name='tony_award_link')
    op.drop_index(op.f('ix_tony_award_link_person_id'), table_name='tony_award_link')
    op.drop_table('tony_award_link')
    # ### end Alembic commands ###
