"""adding the rest of the tables now

Revision ID: c261b391db87
Revises: 744a5120d5be
Create Date: 2021-01-11 11:44:57.130506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c261b391db87'
down_revision = '744a5120d5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
