"""hi yaakov

Revision ID: c72ba32ae5d7
Revises: d99eb9d809ac
Create Date: 2021-01-12 11:35:27.725758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72ba32ae5d7'
down_revision = 'd99eb9d809ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
