"""hi yaakov

Revision ID: cf273f761312
Revises: d9868bef4c91
Create Date: 2021-01-12 11:37:24.885456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf273f761312'
down_revision = 'd9868bef4c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
