"""hi yaakov

Revision ID: d9868bef4c91
Revises: c72ba32ae5d7
Create Date: 2021-01-12 11:36:14.463044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9868bef4c91'
down_revision = 'c72ba32ae5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
