"""hi yaakov

Revision ID: d99eb9d809ac
Revises: 829b9fef152b
Create Date: 2021-01-12 11:35:04.571848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd99eb9d809ac'
down_revision = '829b9fef152b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment='This is the name of the show.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'title',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='This is the name of the show.',
               existing_nullable=True)
    # ### end Alembic commands ###
