"""upgrading this through shell commands

Revision ID: f3af77f05dd6
Revises: 5d1d61e0b4e3
Create Date: 2021-01-10 21:32:06.865555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3af77f05dd6'
down_revision = '5d1d61e0b4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
