"""upgrading this through shell commands

Revision ID: f8b03630dcb4
Revises: 35fc75589ff8
Create Date: 2021-01-10 21:09:14.801819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b03630dcb4'
down_revision = '35fc75589ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shows_closing_date'), 'shows', ['closing_date'], unique=False)
    op.create_index(op.f('ix_shows_opening_date'), 'shows', ['opening_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_opening_date'), table_name='shows')
    op.drop_index(op.f('ix_shows_closing_date'), table_name='shows')
    # ### end Alembic commands ###
